spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cwyy?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /jsps/
      suffix: .jsp
server:
  port: 8008
